"""Canonical page AI-readiness score shared by all audit surfaces.

The score measures only what exists on the merchant's page or was
explicitly supplied by the merchant. Content generated by CatalogReady
never contributes points. Hard gates cap the total when a defect would
mislead an AI shopping agent, so a page with a blocking problem cannot
present a high score.
"""

from __future__ import annotations

from typing import Any

from ..catalog.metrics import METRICS, metric_for
from ..catalog.platforms import (
    PLATFORM_LABELS,
    PLATFORM_SURFACES,
    PLATFORMS,
    platforms_for,
)

_CLAIM_DEDUCTIONS = {"high": 5, "medium": 3, "low": 1}

# Every page/claim finding also deducts by severity, on top of the
# presence checks. Checks measure what exists; findings measure documented
# platform defects — a page dense with defects must not score like a clean
# one just because its basic fields are present.
# GEO-* rules (machine-readable product data) carry higher weight: they are
# the core of AI-shopping readiness, while SEO-* (transport) and CLAIM-*
# (which additionally cap the score) stay at the base weights.
_FINDING_DEDUCTIONS = {"high": 6, "medium": 3, "low": 1}
_GEO_DEDUCTIONS = {"high": 9, "medium": 5, "low": 2}


def _deduction(item: dict[str, Any]) -> int:
    table = (
        _GEO_DEDUCTIONS
        if str(item.get("rule_id", "")).startswith("GEO-")
        else _FINDING_DEDUCTIONS
    )
    return table.get(str(item.get("severity")), 1)


def _metric_breakdown(findings: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Summarize the audited defects without inventing an independent metric score."""

    breakdown: dict[str, dict[str, Any]] = {}
    for metric in METRICS:
        matching = [
            item
            for item in findings
            if (item.get("metric") or metric_for(item.get("rule_id", ""))) == metric
        ]
        deductions = sum(_deduction(item) for item in matching)
        breakdown[metric] = {
            "status": "needs_work" if matching else "clear",
            "findings": len(matching),
            "deductions": deductions,
        }
    return breakdown


def _platform_scores(
    raw_score: int,
    findings: list[dict[str, Any]],
    cap_events: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    """Apply the canonical arithmetic to each platform's relevant rule subset."""

    views: tuple[str, ...] = ("comprehensive", *PLATFORMS)
    output: dict[str, dict[str, Any]] = {}
    for platform in views:
        if platform == "comprehensive":
            relevant_findings = findings
            relevant_caps = cap_events
            label = "Comprehensive"
            surfaces = tuple(
                surface for name in PLATFORMS for surface in PLATFORM_SURFACES[name]
            )
        else:
            relevant_findings = [
                item
                for item in findings
                if platform in (item.get("platforms") or platforms_for(item.get("rule_id", "")))
            ]
            relevant_caps = [
                event for event in cap_events if platform in event["platforms"]
            ]
            label = PLATFORM_LABELS[platform]
            surfaces = PLATFORM_SURFACES[platform]
        deductions = sum(_deduction(item) for item in relevant_findings)
        cap = min((int(event["cap"]) for event in relevant_caps), default=100)
        score = max(1, min(raw_score - deductions, cap))
        output[platform] = {
            "label": label,
            "surfaces": list(surfaces),
            "score": score,
            "status": "ready" if score >= 80 and cap == 100 else "needs_work",
            "raw_score": raw_score,
            "deductions": deductions,
            "deduction_items": [
                {
                    "rule_id": str(item.get("rule_id", "")),
                    "title": str(item.get("title", "Finding")),
                    "metric": str(
                        item.get("metric") or metric_for(item.get("rule_id", ""))
                    ),
                    "severity": str(item.get("severity", "low")),
                    "points": _deduction(item),
                }
                for item in relevant_findings
            ],
            "safety_cap": cap,
            "cap_reasons": [str(event["reason"]) for event in relevant_caps],
            "findings": len(relevant_findings),
            "metrics": _metric_breakdown(relevant_findings),
        }
    return output

PILLARS = (
    "product_identity",
    "offer_completeness",
    "structured_data",
    "decision_evidence",
    "media_variants",
    "claim_grounding",
)


def score_page_readiness(
    evidence_record: dict[str, Any],
    page_audit: dict[str, Any],
    claim_findings: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    product = evidence_record.get("product") or {}
    price = product.get("price") or {}
    summary = page_audit.get("summary") or {}
    page_findings = page_audit.get("findings") or []
    claim_findings = claim_findings or []

    def clean_of(rule_id: str) -> bool:
        return not any(item.get("rule_id") == rule_id for item in page_findings)

    stable_id = bool(
        product.get("id") or product.get("sku") or product.get("gtin") or product.get("mpn")
    )
    identity_checks = {
        "title": (bool(product.get("title")), 5),
        "brand": (bool(product.get("brand")), 5),
        "category": (bool(product.get("category")), 4),
        "stable_identifier": (stable_id, 4),
        "canonical_url": (bool(product.get("url")), 2),
    }
    offer_complete_markup = (
        bool(summary.get("offers")) and clean_of("GEO-OFFER-001") and clean_of("GEO-OFFER-002")
    )
    offer_checks = {
        "price": (bool(price.get("amount")), 6),
        "currency": (bool(price.get("currency")), 4),
        "availability": (bool(product.get("availability")), 6),
        "complete_offer_markup": (offer_complete_markup, 4),
    }
    structured_checks = {
        "product_node": (bool(summary.get("products")), 6),
        "product_identity": (
            bool(summary.get("products"))
            and clean_of("GEO-PRODUCT-002")
            and clean_of("GEO-PRODUCT-003"),
            4,
        ),
        "offer": (offer_complete_markup, 5),
        "canonical": (bool(summary.get("canonical")), 3),
        "valid_json_ld": (summary.get("invalid_json_ld", 0) == 0, 2),
    }
    coverage = summary.get("evidence_coverage") or {}
    review = product.get("review_summary") or {}
    decision_checks = {
        "description": (bool(product.get("description")), 4),
        "specifications": (bool(product.get("specifications")), 4),
        "substantive_page": (int(summary.get("visible_words") or 0) >= 120, 3),
        "evidence_topics": (sum(bool(value) for value in coverage.values()) >= 3, 3),
        "review_evidence": (bool(review.get("rating") and review.get("count")), 1),
    }
    specifications = product.get("specifications") or []
    variant_evidence = any(
        str(item.get("name", "")).lower() in {"color", "size", "pattern"}
        for item in specifications
        if isinstance(item, dict)
    )
    images = product.get("images") or []
    media_checks = {
        "primary_image": (bool(images), 8),
        "multiple_images": (len(images) >= 2, 3),
        "variant_attribute": (variant_evidence, 2),
        "variant_identity": (bool(product.get("sku") or product.get("id")), 2),
    }

    groups = {
        "product_identity": identity_checks,
        "offer_completeness": offer_checks,
        "structured_data": structured_checks,
        "decision_evidence": decision_checks,
        "media_variants": media_checks,
    }
    components: dict[str, dict[str, Any]] = {}
    raw_score = 0
    for name, checks in groups.items():
        score = sum(weight for passed, weight in checks.values() if passed)
        maximum = sum(weight for _, weight in checks.values())
        raw_score += score
        components[name] = {
            "score": score,
            "max_score": maximum,
            "checks": {key: passed for key, (passed, _) in checks.items()},
        }

    claim_deduction = sum(
        _CLAIM_DEDUCTIONS.get(str(item.get("severity")), 1) for item in claim_findings
    )
    claim_score = max(0, 10 - claim_deduction)
    raw_score += claim_score
    components["claim_grounding"] = {
        "score": claim_score,
        "max_score": 10,
        "checks": {
            "no_high_risk_claims": not any(
                item.get("severity") == "high" for item in claim_findings
            ),
            "no_unsupported_claims": not claim_findings,
        },
    }

    cap_events: list[dict[str, Any]] = []
    if any(item.get("severity") == "high" for item in claim_findings):
        cap_events.append(
            {
                "cap": 49,
                "reason": "An unsupported high-risk claim was found in the listing copy.",
                "platforms": PLATFORMS,
            }
        )
    if not clean_of("CLAIM-INJECTION-001"):
        cap_events.append(
            {
                "cap": 49,
                "reason": "The page contains text aimed at manipulating AI agents.",
                "platforms": PLATFORMS,
            }
        )
    if not stable_id:
        cap_events.append(
            {
                "cap": 59,
                "reason": "A stable product identifier is missing.",
                "platforms": PLATFORMS,
            }
        )
    if not (price.get("amount") and price.get("currency") and product.get("availability")):
        cap_events.append(
            {
                "cap": 69,
                "reason": "Price, currency, or availability evidence is incomplete.",
                "platforms": PLATFORMS,
            }
        )
    if not summary.get("products"):
        cap_events.append(
            {
                "cap": 74,
                "reason": "No Product structured data was found on the page.",
                "platforms": ("google", "microsoft"),
            }
        )

    scored_findings = [*page_findings, *claim_findings]
    platform_scores = _platform_scores(raw_score, scored_findings, cap_events)
    comprehensive = platform_scores["comprehensive"]
    deductions = comprehensive["deductions"]
    cap = comprehensive["safety_cap"]
    # Floor at 1: the score is always positive; 1 reads as "essentially
    # nothing is agent-usable" without looking like a rendering bug.
    score = comprehensive["score"]
    return {
        "score": score,
        "raw_score": raw_score,
        "deductions": deductions,
        "status": comprehensive["status"],
        "components": components,
        "safety_cap": cap,
        "cap_reasons": comprehensive["cap_reasons"],
        "platform_scores": platform_scores,
        "observed_ai_visibility": {
            "status": "not_measured",
            "score": None,
        },
    }


__all__ = ["PILLARS", "score_page_readiness"]
