"""Canonical page AI-readiness score shared by all audit surfaces.

The score measures only what exists on the merchant's page or was
explicitly supplied by the merchant. Content generated by CatalogReady
never contributes points. Hard gates cap the total when a defect would
mislead an AI shopping agent, so a page with a blocking problem cannot
present a high score.
"""

from __future__ import annotations

from typing import Any

_CLAIM_DEDUCTIONS = {"high": 5, "medium": 3, "low": 1}

PILLARS = (
    "product_identity",
    "offer_completeness",
    "structured_data",
    "decision_evidence",
    "media_variants",
    "claim_grounding",
)


def score_page_readiness(
    evidence_record: dict[str, Any],
    page_audit: dict[str, Any],
    claim_findings: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    product = evidence_record.get("product") or {}
    price = product.get("price") or {}
    summary = page_audit.get("summary") or {}
    page_findings = page_audit.get("findings") or []
    claim_findings = claim_findings or []

    def clean_of(rule_id: str) -> bool:
        return not any(item.get("rule_id") == rule_id for item in page_findings)

    stable_id = bool(
        product.get("id") or product.get("sku") or product.get("gtin") or product.get("mpn")
    )
    identity_checks = {
        "title": (bool(product.get("title")), 5),
        "brand": (bool(product.get("brand")), 5),
        "category": (bool(product.get("category")), 4),
        "stable_identifier": (stable_id, 4),
        "canonical_url": (bool(product.get("url")), 2),
    }
    offer_complete_markup = bool(summary.get("offers")) and clean_of("GEO-OFFER-001")
    offer_checks = {
        "price": (bool(price.get("amount")), 6),
        "currency": (bool(price.get("currency")), 4),
        "availability": (bool(product.get("availability")), 6),
        "complete_offer_markup": (offer_complete_markup, 4),
    }
    structured_checks = {
        "product_node": (bool(summary.get("products")), 6),
        "product_identity": (bool(summary.get("products")) and clean_of("GEO-PRODUCT-002"), 4),
        "offer": (offer_complete_markup, 5),
        "canonical": (bool(summary.get("canonical")), 3),
        "valid_json_ld": (summary.get("invalid_json_ld", 0) == 0, 2),
    }
    coverage = summary.get("evidence_coverage") or {}
    review = product.get("review_summary") or {}
    decision_checks = {
        "description": (bool(product.get("description")), 4),
        "specifications": (bool(product.get("specifications")), 4),
        "substantive_page": (int(summary.get("visible_words") or 0) >= 120, 3),
        "evidence_topics": (sum(bool(value) for value in coverage.values()) >= 3, 3),
        "review_evidence": (bool(review.get("rating") and review.get("count")), 1),
    }
    specifications = product.get("specifications") or []
    variant_evidence = any(
        str(item.get("name", "")).lower() in {"color", "size", "pattern"}
        for item in specifications
        if isinstance(item, dict)
    )
    images = product.get("images") or []
    media_checks = {
        "primary_image": (bool(images), 8),
        "multiple_images": (len(images) >= 2, 3),
        "variant_attribute": (variant_evidence, 2),
        "variant_identity": (bool(product.get("sku") or product.get("id")), 2),
    }

    groups = {
        "product_identity": identity_checks,
        "offer_completeness": offer_checks,
        "structured_data": structured_checks,
        "decision_evidence": decision_checks,
        "media_variants": media_checks,
    }
    components: dict[str, dict[str, Any]] = {}
    raw_score = 0
    for name, checks in groups.items():
        score = sum(weight for passed, weight in checks.values() if passed)
        maximum = sum(weight for _, weight in checks.values())
        raw_score += score
        components[name] = {
            "score": score,
            "max_score": maximum,
            "checks": {key: passed for key, (passed, _) in checks.items()},
        }

    claim_deduction = sum(
        _CLAIM_DEDUCTIONS.get(str(item.get("severity")), 1) for item in claim_findings
    )
    claim_score = max(0, 10 - claim_deduction)
    raw_score += claim_score
    components["claim_grounding"] = {
        "score": claim_score,
        "max_score": 10,
        "checks": {
            "no_high_risk_claims": not any(
                item.get("severity") == "high" for item in claim_findings
            ),
            "no_unsupported_claims": not claim_findings,
        },
    }

    cap = 100
    cap_reasons: list[str] = []
    if any(item.get("severity") == "high" for item in claim_findings):
        cap = min(cap, 49)
        cap_reasons.append("An unsupported high-risk claim was found in the listing copy.")
    if not stable_id:
        cap = min(cap, 59)
        cap_reasons.append("A stable product identifier is missing.")
    if not (price.get("amount") and price.get("currency") and product.get("availability")):
        cap = min(cap, 69)
        cap_reasons.append("Price, currency, or availability evidence is incomplete.")
    if not summary.get("products"):
        cap = min(cap, 74)
        cap_reasons.append("No Product structured data was found on the page.")

    score = min(raw_score, cap)
    return {
        "score": score,
        "raw_score": raw_score,
        "status": "ready" if score >= 80 and cap == 100 else "needs_work",
        "components": components,
        "safety_cap": cap,
        "cap_reasons": cap_reasons,
        "observed_ai_visibility": {
            "status": "not_measured",
            "score": None,
        },
    }


__all__ = ["PILLARS", "score_page_readiness"]
